### ISSUE TITLE
Header is in wrong position when reuses fragment

### ISSUE THREAD

**Issue by Duncan00** [blipinsk/RecyclerViewHeader#16] opened 2015-07-13 04:00 UTC
Header is in wrong position when reuses fragment.

e.g. scroll down a bit -> remove fragment -> add fragment -> header goes down
e.g.2 scroll down a bit -> home button with not keeping Activity setting in Developer setting -> go back to app -> header goes down

![device-2015-07-13-115640](https://cloud.githubusercontent.com/assets/2004375/8642405/3a7ea5fe-2956-11e5-9e87-dc42a828ec00.png)

**Comment by blipinsk** [comment] 2015-07-29 10:17
This is a known bug. I will be trying to fix that for the next release.

**Comment by shreyanshjain** [comment] 2015-08-06 05:30
Hello blipsink,
Can you tell us when will you be able to release next build, It's because of the project deadline.
Thank you

**Comment by blipinsk** [comment] 2015-08-06 07:49
Hi, 

I can't really give you a specific date, since I'm really short on time currently and can't really spend much time on the library (and this seems to be a not really a simple issue).

If this particular thing is a serious blocker for your project, just move to an `Adapter` that can inflate a header `View` (for example [this](https://github.com/Karumi/HeaderRecyclerView)). It's not that difficult to use, and will solve your issue easily.

Thanks

**Comment by shreyanshjain** [comment] 2015-08-09 06:39
Hello blipsink,

After spending a day, I found a workaround, I don't think it's less efficient but still, you will have to create a new instance of Fragment each time you add it single ton fragment won't work, the problem is with layout manager of recycle view it retains the state that is why it adds the header at the same scroll position where we stopped, but creating a new fragment instance each time you add the fragment, that linear layout manager no longer exists.

**Comment by HarryMMR** [comment] 2015-09-08 06:40
I am having the same issue also. When notifyDataSetChanged( ) is called and if scroll position is down, header would disappear and leave just a blank space in the place of header view. Can update a fix? Thanks

**Comment by AndroidUtils** [comment] 2015-09-08 09:14
I am having the same problem also.... when fragment redisplay in screen

**Comment by shreyanshjain** [comment] 2015-09-08 09:24
@AndroidUtils try creating new instance of fragment and adding it to fragment manager.

**Comment by blipinsk** [comment] 2015-09-08 09:29
It's not an acceptable solution to this problem. `RecyclerViewHeader` state must be saved and restored...

**Comment by HarryMMR** [comment] 2015-09-08 09:30
Creating new instance of fragment won't solve the issue in my case. I'm using background task sync adapter to pull data from server and then loading dynamically in recyclerview.

**Comment by shreyanshjain** [comment] 2015-09-08 09:35
@HarryMMR can you give a screen shot?

**Comment by shreyanshjain** [comment] 2015-09-08 09:36
@blipinsk can you elaborate little more about how can we save and restore the state of the header, I think that would be a better solution.

**Comment by HarryMMR** [comment] 2015-09-08 09:55
Screenshot won't help. Mine is like this.
Contents in recyclerview adapter are refreshed async while I am scrolling the recyclerview. After adapter is refreshed, header view disappears.

I found a bug. Don't know how to fix yet.
I added logcat. Try looking at this piece of code inside RecyclerViewHeader.java.

@SuppressLint("NewApi")
    private void setupHeader(final RecyclerView recycler) {
        recycler.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                mCurrentScroll += dy;
                Log.d(LOG_TAG,"recycler translateY: " + RecyclerViewHeader.this.getTranslationY());
                RecyclerViewHeader.this.setTranslationY(-mCurrentScroll);
            }
        });

Look at the logcat.
It seems like mCurrentScroll keeps getting increased after recycler adapter is refreshed. This will definitely push out the header view further up out of the screen.

Yes, please guide how to save and restore.

Logcat:
09-08 17:42:08.380    5068-5068/? D/RecyclerViewHeader﹕ recycler translateY: -792.0
09-08 17:42:08.470    5068-5068/? D/RecyclerViewHeader﹕ recycler translateY: -821.0
09-08 17:42:08.480    5068-5068/? D/RecyclerViewHeader﹕ recycler translateY: -850.0
09-08 17:42:08.500    5068-5068/? D/RecyclerViewHeader﹕ recycler translateY: -969.0
09-08 17:42:08.520    5068-5068/? D/RecyclerViewHeader﹕ recycler translateY: -989.0
09-08 17:42:08.530    5068-5068/? D/RecyclerViewHeader﹕ recycler translateY: -1006.0
09-08 17:42:08.550    5068-5068/? D/RecyclerViewHeader﹕ recycler translateY: -1022.0
09-08 17:42:08.570    5068-5068/? D/RecyclerViewHeader﹕ recycler translateY: -1038.0
09-08 17:42:08.580    5068-5068/? D/RecyclerViewHeader﹕ recycler translateY: -1052.0
09-08 17:42:08.600    5068-5068/? D/RecyclerViewHeader﹕ recycler translateY: -1065.0
09-08 17:42:08.620    5068-5068/? D/RecyclerViewHeader﹕ recycler translateY: -1077.0
09-08 17:42:08.630    5068-5068/? D/RecyclerViewHeader﹕ recycler translateY: -1088.0
09-08 17:42:08.650    5068-5068/? D/RecyclerViewHeader﹕ recycler translateY: -1098.0
09-08 17:42:08.670    5068-5068/? D/RecyclerViewHeader﹕ recycler translateY: -1108.0
09-08 17:42:08.680    5068-5068/? D/RecyclerViewHeader﹕ recycler translateY: -1116.0
09-08 17:42:08.780    5068-5068/? D/RecyclerViewHeader﹕ recycler translateY: -1124.0
09-08 17:42:09.880    5068-5068/? D/RecyclerViewHeader﹕ recycler translateY: -1136.0

**Comment by HarryMMR** [comment] 2015-09-08 13:44
Fixed the problem. Might not be the best solution. But it works for me. After notifyDataSetChanged() is called and recyclerview is refreshed, I set mCurrentScroll to 0 by using setter method. This brings back the header view back to its original position.

**Comment by shreyanshjain** [comment] 2015-09-08 13:45
@HarryMMR anyway its a solution

**Comment by stasbar** [comment] 2015-10-03 15:33
@HarryMMR how do you set mCurrentScroll to 0 ? In Adapter ?

**Comment by HarryMMR** [comment] 2015-10-05 02:14
@stasbar I found that setting mCurrentScroll to 0 doesn't really fix the issue. Finally I read stackoverflow discussion and implemented my own adapter. It's much better and not that hard to implement. 

http://stackoverflow.com/questions/26448717/android-5-0-add-header-footer-to-a-recyclerview

**Comment by Mithrandir21** [comment] 2016-03-09 22:41
I've found out why the header gets mis-positioned.
In the line
`RecyclerViewHeader.this.setTranslationY(-mCurrentScroll);`
"mCurrentScroll" is 0 when attempting to re-create for example a Fragment.

I will attempt to fix it and post my solution.

**Comment by blipinsk** [comment] 2016-03-09 22:42
You didn't really have to look for the issue, I named the issue before

> It's not an acceptable solution to this problem. RecyclerViewHeader state must be saved and restored...

**Comment by Mithrandir21** [comment] 2016-03-09 23:13
Nonetheless, I found a way to work around the issue for me:

First add a new class variable:
`private FrameLayout rootParent;`

Second, add this line as the first in the 
`public void attachTo( RecyclerView recycler, boolean headerAlreadyAligned )` method:
```if( rootParent != null ) { rootParent.removeAllViews(); }```

Third, change the `FrameLayout newRootParent` to the `rootParent` in the `setupAlignment`.


This worked for me.

**Comment by blipinsk** [comment] 2016-04-07 13:56
Fixed in the 2.0.0 Version.

**Closed by blipinsk** 2016-04-07 13:56 UTC
Labels: Bug, Fixed / Implemented
