### ISSUE TITLE
Header is not aligned correctly when screen orientation is changed

### ISSUE THREAD

**Issue by jakubkrolewski** [blipinsk/RecyclerViewHeader#41] opened 2016-02-11 11:57 UTC
Steps to reproduce:
1. Remove `android:screenOrientation="portrait"` from the sample app manifest to enable support for origination changes.
2. Scroll the list a little bit
3. Rotate the screen

Result:
The header is not aligned correctly. It overlaps with list items.

**Comment by blipinsk** [comment] 2016-02-11 12:31
Dupe of #16

**Comment by blipinsk** [comment] 2016-02-11 12:32
Steps to reproduce are different than in #16 but the underlying issue is the same.

**Closed by blipinsk** 2016-02-11 12:31 UTC
