### ISSUE TITLE
Exception happened in `onTouch()`

### ISSUE THREAD

**Issue by Zhuinden** [blipinsk/RecyclerViewHeader#69] opened 2017-11-15 13:17 UTC
We got an error from an LG device (LG K10 LTE) because of this code:

``` java
            MotionEvent recyclerEvent =
                    MotionEvent.obtain(event.getDownTime(),
                            event.getEventTime(),
                            event.getAction(),
                            event.getX() - horizontalDiff,
                            event.getY() - verticalDiff,
                            event.getMetaState());
```

Exception: 

```
Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetPointerId(MotionEvent.java)
       at android.view.MotionEvent.getPointerId(MotionEvent.java:2037)
       at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2916)
```

**Comment by blipinsk** [comment] 2018-04-24 18:36
dupe of #68

**Closed by blipinsk** 2018-04-24 18:36 UTC
