### ISSUE TITLE
Error: java.lang.IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by nb312** [blipinsk/RecyclerViewHeader#70] opened 2017-11-27 07:23 UTC
E/AndroidRuntime(26520): FATAL EXCEPTION: main

E/AndroidRuntime(26520): java.lang.IllegalArgumentException: pointerIndex out of range

E/AndroidRuntime(26520): 	at android.view.MotionEvent.nativeGetPointerId(Native Method)

E/AndroidRuntime(26520): 	at android.view.MotionEvent.getPointerId(MotionEvent.java:1934)

E/AndroidRuntime(26520): 	at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2840)

E/AndroidRuntime(26520): 	at com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader$RecyclerViewDelegate.onTouchEvent(RecyclerViewHeader.java:327)

E/AndroidRuntime(26520): 	at com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader.onTouchEvent(RecyclerViewHeader.java:183)

E/AndroidRuntime(26520): 	at android.view.View.dispatchTouchEvent(View.java:7347)

E/AndroidRuntime(26520): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2278)

E/AndroidRuntime(26520): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1975)

E/AndroidRuntime(26520): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2284)

E/AndroidRuntime(26520): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1989)

E/AndroidRuntime(26520): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2284)

E/AndroidRuntime(26520): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1989)

E/AndroidRuntime(26520): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2284)

E/AndroidRuntime(26520): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1989)

E/AndroidRuntime(26520): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2284)

E/AndroidRuntime(26520): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1989)

E/AndroidRuntime(26520): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2284)

E/AndroidRuntime(26520): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1989)

E/AndroidRuntime(26520): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2284)

E/AndroidRuntime(26520): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1989)

E/AndroidRuntime(26520): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2284)

E/AndroidRuntime(26520): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1989)

E/AndroidRuntime(26520): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2010)

E/AndroidRuntime(26520): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1447)

E/AndroidRuntime(26520): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2455)

E/AndroidRuntime(26520): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1958)

E/AndroidRuntime(26520): 	at android.view.View.dispatchPointerEvent(View.java:7538)

E/AndroidRuntime(26520): 	at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3766)

E/AndroidRuntime(26520): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3649)

E/AndroidRuntime(26520): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4961)

E/AndroidRuntime(26520): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4921)

E/AndroidRuntime(26520): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5080)

E/AndroidRuntime(26520): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:190)

E/AndroidRuntime(26520): 	at android.os.MessageQueue.nativePollOnce(Native Method)

E/AndroidRuntime(26520): 	at android.os.MessageQueue.next(MessageQueue.java:128)

E/AndroidRuntime(26520): 	at android.os.Looper.loop(Looper.java:151)

E/AndroidRuntime(26520): 	at android.app.ActivityThread.main(ActivityThread.java:5468)

E/AndroidRuntime(26520): 	at java.lang.reflect.Method.invokeNative(Native Method)

E/AndroidRuntime(26520): 	at java.lang.reflect.Method.invoke(Method.java:525)

E/AndroidRuntime(26520): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:934)

E/AndroidRuntime(26520): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:701)

E/AndroidRuntime(26520): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by blipinsk** [comment] 2018-04-24 18:36
dupe of #68

**Closed by blipinsk** 2018-04-24 18:36 UTC
Labels: Duplicate
