### ISSUE TITLE
header disappear

### ISSUE THREAD

**Issue by rehacktive** [blipinsk/RecyclerViewHeader#29] opened 2015-11-04 13:03 UTC
Hello,
I'm using this layout:

<RelativeLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:android="http://schemas.android.com/apk/res/android" android:background="@color/light_grey">

    <android.support.v4.widget.SwipeRefreshLayout
        android:id="@+id/swipeRefreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <RecyclerView
            android:id="@+id/recyclerview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:columnWidth="@dimen/column_width"
            android:clipToPadding="false"
            />

    </android.support.v4.widget.SwipeRefreshLayout>

    <com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader
        android:id="@+id/header"
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        >
        <include
            layout="@layout/filter_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>

    </com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader>

</RelativeLayout>

The Recycler uses a StaggeredGridLayoutManager.
Everytime I scroll down a bit and I go back to the top, the header is gone.

Is there something I can do differently?

thanks!

**Comment by blipinsk** [comment] 2015-11-04 13:12
Hi,

why don't you try [this](https://github.com/blipinsk/RecyclerViewHeader/issues/19#issuecomment-135731288) hierarchy. I think it might be due to the usage of the `SwipeRefreshLayout` (and you need to keep your `RecyclerViewHeader` inside of it as well).

Let me know if it helped

**Comment by rehacktive** [comment] 2015-11-04 13:30
I've tried and it still doesn't work.
I've tried also to remove completely the swipe to refresh.
Now it's:

<FrameLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:android="http://schemas.android.com/apk/res/android" android:background="@color/light_grey">
    
    <RecyclerView
        android:id="@+id/recyclerview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:columnWidth="@dimen/column_width"
        android:clipToPadding="false"

        />

    <com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader
        android:id="@+id/header"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <include
            layout="@layout/filter_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>

    </com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader>
    
</FrameLayout>

and I simply attach it with:

header.attachTo(extendedRecyclerView,true);

(on the fragment).
After a scroll down and a quick scroll up...it appears not at the top, but in a wrong position.
Ideas?

(btw, thanks for your prompt reply!)

**Comment by rehacktive** [comment] 2015-11-04 13:31
it happens only if the scroll to the top is very quick!

**Comment by blipinsk** [comment] 2015-11-04 14:38
It might be some incompatibility with `StaggeredGridLayoutManager`, can you try a different `LayoutManager` (just for the sake of debugging)?

**Comment by rehacktive** [comment] 2015-11-04 16:37
I think it's this same issue https://github.com/blipinsk/RecyclerViewHeader/issues/16
any fix?

**Comment by blipinsk** [comment] 2015-11-04 17:06
I honestly don't think it is. The other issue is caused by the fact that the `RecyclerView's` state is being restored, and `RecyclerViewHeader's` is not. And I'm currently working on fixing that. Your issue involves scrolling... there is no state saving-restoration when you're scrolling.

**Comment by SelimEmre** [comment] 2015-11-18 06:01
Hi everyone,
I'm using RecycleViewHeader in swipeRefreshLayout.. and LinearLayoutManager..
Firstly everything is OK. But when I refresh with SwipeRefreshLayout, header recycleview slipping down
Normal situation;
![1](https://cloud.githubusercontent.com/assets/9084130/11233728/7a85fd28-8dc9-11e5-9502-8eb13ff0a433.PNG)
And Refreshed Situation;
![2](https://cloud.githubusercontent.com/assets/9084130/11233734/895667b6-8dc9-11e5-8785-bb8782e9f83e.PNG)

And here its my layout;

   < android.support.v4.widget.SwipeRefreshLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/swipeRefreshFirsat"
        >
< FrameLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    android:visibility="gone"
    android:focusable="true"
    android:focusableInTouchMode="true"
    android:layout_below="@+id/eksikler_linear"
    android:id="@+id/firsatlar_linear"
    android:paddingLeft="10dp"
    android:paddingRight="10dp"
    android:paddingTop="10dp"
    >
    < com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader
        android:id="@+id/header"
        android:layout_width="match_parent"
        android:layout_height="60dp"
        android:layout_gravity="center_horizontal|top">
        < TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textAppearance="?android:attr/textAppearanceSmall"
            android:text="Yaşadığın Şehrin Fırsatları Listeleniyor"
            android:background="#777"
            android:textColor="@color/abc_primary_text_disable_only_material_dark"
            android:id="@+id/txt_sehir_firsat"
            android:padding="5dp"
            android:layout_marginLeft="10dp"
            android:layout_alignParentTop="true"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="true" />
        < TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textAppearance="?android:attr/textAppearanceSmall"
            android:background="#5bc0de"
            android:textColor="@color/abc_primary_text_disable_only_material_dark"
            android:layout_marginTop="5dp"
            android:padding="5dp"
            android:layout_marginLeft="10dp"
            android:text="Sehir"
            android:id="@+id/txt_sehir"
            android:layout_below="@+id/txt_sehir_firsat"/>
    </ com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader>
    < android.support.v7.widget.RecyclerView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/firsatlar_liste"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="10dp"
            android:layout_below="@+id/txt_sehir"
            />
</ FrameLayout>
    </ android.support.v4.widget.SwipeRefreshLayout>

And here it's my adapter;

list=(RecyclerView)getActivity().findViewById(R.id.firsatlar_liste);
mLayoutManager = new LinearLayoutManager(getActivity());
mLayoutManager.setOrientation(LinearLayoutManager.VERTICAL);
list.setLayoutManager(mLayoutManager);
list.setHasFixedSize(true);
list.setItemAnimator(new DefaultItemAnimator());
list.setAdapter(adapter);
mRecyclerHeader = (RecyclerViewHeader) getActivity().findViewById(R.id.header);
mRecyclerHeader.attachTo(list, true);

Please help me, Im waiting your message

**Comment by blipinsk** [comment] 2015-11-18 09:51
I don't see a problem with your code (at least at first glance)... Can you try (just for the sake of debugging) disable your `ItemAnimator` (comment `list.setItemAnimator(new DefaultItemAnimator());` line) and see if the issue persists?

**Comment by SelimEmre** [comment] 2015-11-18 10:20
Unfortunately, nothing has changed

**Comment by blipinsk** [comment] 2015-11-18 10:24
Can you show us also the way you're setting up your `SwipeRefreshLayout`(with your implementation of `OnRefreshListener`)?

**Comment by SelimEmre** [comment] 2015-11-18 11:58
swipeRefreshLayout = (SwipeRefreshLayout) rootView.findViewById(R.id.swipeRefreshFirsat);

        swipeRefreshLayout.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
            @Override
            public void onRefresh() {
                if (session.isOnline()) {
                    new fillAdapter().execute();
                } else {
                    Toast.makeText(getActivity(), "Lütfen İnternetizini Kontrol Ediniz.", Toast.LENGTH_SHORT).show();
                }
            }
        });
in fillAdapter class I use call http request and 
protected void onPreExecute() {
...
}
public Void doInBackground(Void... params) {
...
}
onPostExecute(){
 list=(RecyclerView)getActivity().findViewById(R.id.firsatlar_liste);
 list.setLayoutManager(new LinearLayoutManager(getActivity()));
 list.setAdapter(new FirsatListviewAdapter(getActivity(),firsatListe));
 list.setHasFixedSize(true);
 mRecyclerHeader = (RecyclerViewHeader) getActivity().findViewById(R.id.header);
 mRecyclerHeader.attachTo(list, true);
}
on post execute I filling in adapter again..

**Comment by SelimEmre** [comment] 2015-11-19 18:48
Can anyone help me?

**Comment by blipinsk** [comment] 2015-11-19 21:49
Why do you exactly reinitialize everything in your `onPostExecute`? Why don't you just clear items in your adapter? My guess is, something is saving its state and restoring it after you reinitialize everything. As for now `RecyclerViewHeader` is missing the ability to save and restore its state (see issue#16).

**Comment by SelimEmre** [comment] 2015-11-20 15:26
My RecycleView Data is changeable in my server. I must to refresh every time and getting data..
I found the problem. When I added mRecyclerHeader.attachTo(list,true); The problem is happening....

**Comment by blipinsk** [comment] 2015-11-20 16:29
Maybe you didn't understand my question 100%. Let me put it this way:
Why do you call this:

    list=(RecyclerView)getActivity().findViewById(R.id.firsatlar_liste);
    list.setLayoutManager(new LinearLayoutManager(getActivity()));
    list.setAdapter(new FirsatListviewAdapter(getActivity(),firsatListe));
    list.setHasFixedSize(true);
    mRecyclerHeader = (RecyclerViewHeader) getActivity().findViewById(R.id.header);
    mRecyclerHeader.attachTo(list, true);

instead of something like this (assuming you have stored your `FirsatListviewAdapter` in a field `mAdapter`, and you have a method to clear its contents):

    mAdapter.clear();
    mAdapter.notifyDataSetChanged();

--

> I found the problem. When I added mRecyclerHeader.attachTo(list,true); The problem is happening....

It only strenghtens my belief in my opinion that the issue is due to you reinitializing everything instead of just changing data of the adapter.

**Comment by SelimEmre** [comment] 2015-11-28 11:04
Hi again :) 
I solved this problem but now I have new problem. in my mainfest file android:configChanges=
                "keyboard|keyboardHidden|screenSize|screenLayout|layoutDirection|orientation" using in my fragment activity. When I rotate app, recycleviewheader elements is disappeared. What should I do?

**Comment by moorthysubu** [comment] 2016-03-05 10:35
@SelimEmre how do you solve that header disappeared issue.I also struck with issue around two days.Can you please give me your suggestions.

**Comment by SelimEmre** [comment] 2016-03-05 13:34
Can you try latest version of library ?
compile 'com.android.support:appcompat-v7:23.2.0'
compile 'com.android.support:design:23.2.0'

**Comment by moorthysubu** [comment] 2016-03-08 06:43
yes i have tried but in that library give parallax effect & bounce effect so client don't want those things in app

**Comment by SelimEmre** [comment] 2016-03-09 19:17
Can you write your codes ?

**Comment by blipinsk** [comment] 2016-04-07 13:55
Fixed in the 2.0.0 Version.

**Closed by blipinsk** 2016-04-07 13:55 UTC
Labels: Fixed / Implemented
