### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException pointerIndex out of range

### ISSUE THREAD

**Issue by TaifRaoof** [blipinsk/RecyclerViewHeader#72] opened 2018-04-24 16:57 UTC
**Hi this error appear to some users**  

Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetPointerId(MotionEvent.java)
       at android.view.MotionEvent.getPointerId(MotionEvent.java:2371)
       at android.support.v7.widget.RecyclerView.onPointerUp(RecyclerView.java:3134)
       at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:3089)
       at com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader$RecyclerViewDelegate.onTouchEvent(RecyclerViewHeader.java:327)
       at com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader.onTouchEvent(RecyclerViewHeader.java:183)
       at android.view.View.dispatchTouchEvent(View.java:10779)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2858)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2534)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)

**Comment by blipinsk** [comment] 2018-04-24 18:36
dupe of #68

**Closed by blipinsk** 2018-04-24 18:36 UTC
